id: I72F79B9C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T05:23:19+00:00'
last_modified: '2022-06-08T10:33:35.001033+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18499
  title: ལ་མོ་བདེ་ཆེན་ཆོས་འཁོར་གླིང་གི་ལོ་རྒྱུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    015B:
      image_group_id: I8LS18501
      title: ''
      total_pages: 318
      order: 1
      base_file: 015B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
