id: P009374
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W8LS18499
  title: ལ་མོ་བདེ་ཆེན་ཆོས་འཁོར་གླིང་གི་ལོ་རྒྱུས།
  author: ''
  volumes:
    e68da43b553f4c8eba08b31e157b3317:
      image_group_id: I8LS18501
      title: ''
      volume_number: 1
      total_pages: 318
      base_file: v001.txt
